/**
 * class-data.js
 * Datos completos de las 12 clases del juego
 */

export const classData = {
    warrior: {
        name: 'Guerrero',
        icon: '⚔️',
        category: 'Combate',
        tags: ['Combate'],
        hp: '+30%',
        mana: '-50%',
        expert: ['Combate', 'Defensa'],
        armor: 'Pesada ✅',
        magic: '❌',
        role: 'Tanque frontal',
        description: 'Maestro del combate cuerpo a cuerpo, resiste toneladas de daño.',
        equipment: 'Armaduras pesadas, armas grandes',
        startItems: ['Espada', 'Escudo', 'Armadura de Cuero']
    },
    paladin: {
        name: 'Paladín',
        icon: '🛡️',
        category: 'Combate',
        tags: ['Híbrido', 'Sagrado'],
        hp: '+20%',
        mana: '-20%',
        expert: ['Combate', 'Defensa', 'Liderazgo'],
        armor: 'Pesada ✅',
        magic: 'Divina ✅',
        role: 'Tanque con curación',
        description: 'Guerrero sagrado que combina fuerza y magia divina.',
        equipment: 'Armaduras pesadas, armas y magia',
        startItems: ['Martillo', 'Escudo de Hierro', 'Armadura de Placas']
    },
    mage: {
        name: 'Mago',
        icon: '🔮',
        category: 'Mágico',
        tags: ['Magia', 'DPS'],
        hp: '-30%',
        mana: '+100%',
        expert: ['Magia', 'Meditar'],
        armor: 'Ligera',
        magic: 'Arcana ✅ (requiere bastón)',
        role: 'DPS mágico',
        description: 'Devastador con hechizos pero frágil en combate físico.',
        equipment: 'Túnicas, bastones mágicos',
        startItems: ['Bastón', 'Túnica de Mago', 'Capucha Mágica']
    },
    cleric: {
        name: 'Clérigo',
        icon: '✝️',
        category: 'Mágico',
        tags: ['Curación', 'Soporte'],
        hp: 'Normal',
        mana: '+20%',
        expert: ['Magia divina', 'Liderazgo'],
        armor: 'Media',
        magic: 'Divina ✅',
        role: 'Sanador',
        description: 'Protector sagrado, imposible que robe (mod 4.0).',
        bonus: '+30% curación',
        equipment: 'Túnicas, mazas, escudos',
        startItems: ['Maza', 'Escudo', 'Túnica Blanca']
    },
    druid: {
        name: 'Druida',
        icon: '🌿',
        category: 'Versátil',
        tags: ['Naturaleza', 'Soporte'],
        hp: '-10%',
        mana: '+50%',
        expert: ['Domar', 'Supervivencia'],
        armor: 'Ligera',
        magic: 'Natural ✅',
        role: 'Soporte/DPS',
        description: 'Guardián de la naturaleza con habilidades de transformación.',
        bonus: '+30% domar, +50% naturaleza',
        equipment: 'Túnicas naturales, bastones',
        startItems: ['Bastón Natural', 'Túnica Verde']
    },
    bard: {
        name: 'Bardo',
        icon: '🎵',
        category: 'Versátil',
        tags: ['Soporte', 'Social'],
        hp: '-15%',
        mana: 'Normal',
        expert: ['Comercio', 'Liderazgo'],
        armor: 'Ligera',
        magic: 'Limitada',
        role: 'Apoyo con buffs',
        description: 'Artista versátil que usa música y carisma.',
        bonus: '+50% carisma',
        equipment: 'Instrumentos, dagas',
        startItems: ['Daga', 'Laúd', 'Ropa Elegante']
    },
    assassin: {
        name: 'Asesino',
        icon: '🗡️',
        category: 'Furtivo',
        tags: ['DPS', 'Sigilo'],
        hp: '-10%',
        mana: '-30%',
        critical: '+40%',
        expert: ['Ocultarse', 'Apuñalar'],
        armor: 'Ligera',
        magic: '❌',
        role: 'DPS burst',
        description: 'Letal desde las sombras con golpes críticos devastadores.',
        bonus: '+50% tiempo oculto',
        equipment: 'Armadura ligera, dagas, arcos',
        startItems: ['Daga', 'Armadura Negra', 'Capucha']
    },
    thief: {
        name: 'Ladrón',
        icon: '🦹',
        category: 'Furtivo',
        tags: ['Robo', 'Evasión'],
        hp: '-15%',
        mana: '-40%',
        steal: '+50%',
        expert: ['Robar', 'Ocultarse'],
        armor: 'Ligera',
        magic: '❌',
        role: 'Robo y evasión',
        description: 'Maestro del sigilo y el robo, escurridizo en combate.',
        equipment: 'Armadura ligera, dagas',
        startItems: ['Daga', 'Armadura de Cuero', 'Ganzúas']
    },
    bandit: {
        name: 'Bandido',
        icon: '🏴‍☠️',
        category: 'Furtivo',
        tags: ['DPS', 'Híbrido'],
        hp: '+10%',
        mana: '-40%',
        critical: '+20%',
        expert: ['Combate', 'Wrestling'],
        armor: 'Media',
        magic: '❌',
        role: 'DPS físico',
        description: 'Guerrero pícaro que combina fuerza y astucia.',
        bonus: 'Ocultar -50% tiempo',
        equipment: 'Armaduras medias, armas variadas',
        startItems: ['Espada', 'Armadura de Cuero']
    },
    hunter: {
        name: 'Cazador',
        icon: '🏹',
        category: 'Especializado',
        tags: ['DPS Distancia', 'Supervivencia'],
        hp: 'Normal',
        mana: '-40%',
        bowDamage: '+30%',
        expert: ['Arco', 'Domar', 'Supervivencia'],
        armor: 'Media',
        magic: '❌',
        role: 'DPS a distancia',
        description: 'Maestro del arco y la naturaleza.',
        bonus: '+20% domar',
        equipment: 'Armadura de cuero, arcos',
        startItems: ['Arco', 'Flechas', 'Armadura de Cuero']
    },
    worker: {
        name: 'Trabajador',
        icon: '🔨',
        category: 'Especializado',
        tags: ['Oficios', 'Crafteo'],
        hp: 'Normal',
        mana: '-50%',
        resources: '+100%',
        expert: ['TODOS los oficios'],
        armor: 'Ligera',
        magic: '❌',
        role: 'Recolección y crafteo',
        description: 'Maestro artesano, extrae el DOBLE de recursos.',
        bonus: 'Aprende oficios 2x más rápido',
        equipment: 'Herramientas de trabajo',
        startItems: ['Pico', 'Hacha', 'Martillo']
    },
    pirate: {
        name: 'Pirata',
        icon: '🏴‍☠️',
        category: 'Especializado',
        tags: ['Naval', 'Saqueo'],
        hp: '+10%',
        mana: '-40%',
        naval: '+50%',
        expert: ['Navegación'],
        armor: 'Media',
        magic: '❌',
        role: 'DPS naval',
        description: 'Corsario maestro de la navegación.',
        bonus: 'Puede ocultarse en agua',
        equipment: 'Sables, pistolas',
        startItems: ['Sable', 'Pistola', 'Sombrero de Pirata']
    }
};

export const classCategories = {
    'Combate': ['warrior', 'paladin'],
    'Mágico': ['mage', 'cleric'],
    'Versátil': ['druid', 'bard'],
    'Furtivo': ['assassin', 'thief', 'bandit'],
    'Especializado': ['hunter', 'worker', 'pirate']
};

export const beginnersClasses = ['worker', 'warrior', 'hunter'];
export const advancedClasses = ['mage', 'assassin', 'paladin'];
